apiVersion: v1
kind: ServiceAccount
metadata:
  name: counting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: counting-service
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        name: counting-service
    spec:
      serviceAccountName: counting
      containers:
        - name: application
          image: erenalidal/counting-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: counting
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    name: counting-service